apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)

    scope "/tasks" do
      get("/create_contract_methods", TaskController, :create_contract_methods, as: :create_contract_methods)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/api_router.ex
defmodule RPCTranslatorForwarder do
  @moduledoc """
  Phoenix router limits forwarding,
  so this module is to forward old paths for backward compatibility
  """
  alias BlockScoutWeb.API.RPC.RPCTranslator
  defdelegate init(opts), to: RPCTranslator
  defdelegate call(conn, opts), to: RPCTranslator
end

defmodule BlockScoutWeb.ApiRouter do
  @moduledoc """
  Router for API
  """
  use BlockScoutWeb, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/v1", as: :api_v1 do
    pipe_through(:api)
    alias BlockScoutWeb.API.{RPC, V1}
    alias BlockScoutWeb.API.V1.HealthController

    get("/health", HealthController, :health)

    if Application.get_env(:block_scout_web, __MODULE__)[:reading_enabled] do
      get("/supply", V1.SupplyController, :supply)
      post("/eth-rpc", RPC.EthController, :eth_request)
    end

    if Application.get_env(:block_scout_web, __MODULE__)[:writing_enabled] do
      post("/decompiled_smart_contract", V1.DecompiledSmartContractController, :create)
      post("/verified_smart_contracts", V1.VerifiedSmartContractController, :create)
    end

    if Application.get_env(:block_scout_web, __MODULE__)[:reading_enabled] do
      forward("/", RPC.RPCTranslator, %{
        "block" => {RPC.BlockController, []},
        "account" => {RPC.AddressController, []},
        "logs" => {RPC.LogsController, []},
        "token" => {RPC.TokenController, []},
        "stats" => {RPC.StatsController, []},
        "contract" => {RPC.ContractController, [:verify]},
        "transaction" => {RPC.TransactionController, []}
      })
    end
  end

  # For backward compatibility. Should be removed
  scope "/" do
    pipe_through(:api)
    alias BlockScoutWeb.API.RPC

    if Application.get_env(:block_scout_web, __MODULE__)[:reading_enabled] do
      post("/eth-rpc", RPC.EthController, :eth_request)

      forward("/", RPCTranslatorForwarder, %{
        "block" => {RPC.BlockController, []},
        "account" => {RPC.AddressController, []},
        "logs" => {RPC.LogsController, []},
        "token" => {RPC.TokenController, []},
        "stats" => {RPC.StatsController, []},
        "contract" => {RPC.ContractController, [:verify]},
        "transaction" => {RPC.TransactionController, []}
      })
    end
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL
  alias BlockScoutWeb.{ApiRouter, WebRouter}

  if Application.get_env(:block_scout_web, ApiRouter)[:wobserver_enabled] do
    forward("/wobserver", Wobserver.Web.Router)
  end

  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/api", ApiRouter)

  if Application.get_env(:block_scout_web, ApiRouter)[:reading_enabled] do
    # Needs to be 200 to support the schema introspection for graphiql
    @max_complexity 200

    forward("/graphql", Absinthe.Plug,
      schema: BlockScoutWeb.Schema,
      analyze_complexity: true,
      max_complexity: @max_complexity
    )

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: BlockScoutWeb.Schema,
      interface: :advanced,
      default_query: GraphQL.default_query(),
      socket: BlockScoutWeb.UserSocket,
      analyze_complexity: true,
      max_complexity: @max_complexity
    )
  else
    scope "/", BlockScoutWeb do
      pipe_through(:browser)
      get("/api-docs", PageNotFoundController, :index)
      get("/eth-rpc-api-docs", PageNotFoundController, :index)
    end
  end

  scope "/", BlockScoutWeb do
    pipe_through(:browser)

    get("/api-docs", APIDocsController, :index)
    get("/eth-rpc-api-docs", APIDocsController, :eth_rpc)
  end

  url_params = Application.get_env(:block_scout_web, BlockScoutWeb.Endpoint)[:url]
  api_path = url_params[:api_path]
  path = url_params[:path]

  if path != api_path do
    scope to_string(api_path) <> "/verify_smart_contract" do
      pipe_through(:api)

      post("/contract_verifications", BlockScoutWeb.AddressContractVerificationController, :create)
    end
  else
    scope "/verify_smart_contract" do
      pipe_through(:api)

      post("/contract_verifications", BlockScoutWeb.AddressContractVerificationController, :create)
    end
  end

  # if path != api_path do
  #   scope to_string(api_path) <> "/verify_smart_contract" do
  #     pipe_through(:api)

  #     if Application.get_env(:explorer, Explorer.ThirdPartyIntegrations.Sourcify)[:enabled] do
  #       post("/contract_verifications", BlockScoutWeb.AddressContractVerificationController, :create)
  #     else
  #       post("/contract_verifications", BlockScoutWeb.AddressContractVerificationViaFlattenedCodeController, :create)
  #     end
  #   end
  # else
  #   scope "/verify_smart_contract" do
  #     pipe_through(:api)

  #     if Application.get_env(:explorer, Explorer.ThirdPartyIntegrations.Sourcify)[:enabled] do
  #       post("/contract_verifications", BlockScoutWeb.AddressContractVerificationController, :create)
  #     else
  #       post("/contract_verifications", BlockScoutWeb.AddressContractVerificationViaFlattenedCodeController, :create)
  #     end
  #   end
  # end

  if Application.get_env(:block_scout_web, WebRouter)[:enabled] do
    forward("/", BlockScoutWeb.WebRouter)
  else
    scope "/", BlockScoutWeb do
      pipe_through(:browser)

      forward("/", APIDocsController, :index)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/web_router.ex
defmodule BlockScoutWeb.WebRouter do
  @moduledoc """
  Router for web app
  """
  use BlockScoutWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
    plug(BlockScoutWeb.ChecksumAddress)
  end

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market-history-chart", Chain.MarketHistoryChartController,
      only: [:show],
      singleton: true
    )

    resources("/transaction-history-chart", Chain.TransactionHistoryChartController,
      only: [:show],
      singleton: true
    )

    resources "/block", BlockController, only: [:show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    resources("/blocks", BlockController, as: :blocks, only: [:index])

    resources "/blocks", BlockController, as: :block_secondary, only: [:show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    get("/validators", StakesController, :index, as: :validators, assigns: %{filter: :validator})
    get("/active-pools", StakesController, :index, as: :active_pools, assigns: %{filter: :active})
    get("/inactive-pools", StakesController, :index, as: :inactive_pools, assigns: %{filter: :inactive})

    resources("/pending-transactions", PendingTransactionController, only: [:index])

    resources("/recent-transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal-transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/raw-trace",
        TransactionRawTraceController,
        only: [:index],
        as: :raw_trace
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token-transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources("/tokens", TokensController, only: [:index])

    resources("/bridged-tokens", BridgedTokensController, only: [:index, :show])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal-transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/decompiled-contracts",
        AddressDecompiledContractController,
        only: [:index],
        as: :decompiled_contract
      )

      resources(
        "/logs",
        AddressLogsController,
        only: [:index],
        as: :logs
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new],
        as: :verify_contract
      )

      resources(
        "/verify-via-flattened-code",
        AddressContractVerificationViaFlattenedCodeController,
        only: [:new],
        as: :verify_contract_via_flattened_code
      )

      resources(
        "/verify-via-json",
        AddressContractVerificationViaJsonController,
        only: [:new],
        as: :verify_contract_via_json
      )

      resources(
        "/verify-via-standard-json-input",
        AddressContractVerificationViaStandardJsonInputController,
        only: [:new],
        as: :verify_contract_via_standard_json_input
      )

      resources(
        "/verify-vyper-contract",
        AddressContractVerificationVyperController,
        only: [:new],
        as: :verify_vyper_contract
      )

      resources(
        "/read-contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources(
        "/read-proxy",
        AddressReadProxyController,
        only: [:index, :show],
        as: :read_proxy
      )

      resources(
        "/write-contract",
        AddressWriteContractController,
        only: [:index, :show],
        as: :write_contract
      )

      resources(
        "/write-proxy",
        AddressWriteProxyController,
        only: [:index, :show],
        as: :write_proxy
      )

      resources(
        "/token-transfers",
        AddressTokenTransferController,
        only: [:index],
        as: :token_transfers
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token-transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token-balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin-balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin-balances/by-day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/token", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token-transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read-contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token-holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )

      resources(
        "/instance",
        Tokens.InstanceController,
        only: [:show],
        as: :instance
      ) do
        resources(
          "/token-transfers",
          Tokens.Instance.TransferController,
          only: [:index],
          as: :transfer
        )

        resources(
          "/metadata",
          Tokens.Instance.MetadataController,
          only: [:index],
          as: :metadata
        )

        resources(
          "/token-holders",
          Tokens.Instance.HolderController,
          only: [:index],
          as: :holder
        )
      end
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token_secondary do
      resources(
        "/token-transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read-contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token-holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )

      resources(
        "/instance",
        Tokens.InstanceController,
        only: [:show],
        as: :instance
      ) do
        resources(
          "/token-transfers",
          Tokens.Instance.TransferController,
          only: [:index],
          as: :transfer
        )

        resources(
          "/metadata",
          Tokens.Instance.MetadataController,
          only: [:index],
          as: :metadata
        )

        resources(
          "/token-holders",
          Tokens.Instance.HolderController,
          only: [:index],
          as: :holder
        )
      end
    end

    resources(
      "/smart-contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/address-counters", AddressController, :address_counters)

    get("/search", ChainController, :search)

    get("/search-logs", AddressLogsController, :search_logs)

    get("/search-results", SearchController, :search_results)

    get("/csv-export", CsvExportController, :index)

    post("/captcha", CaptchaController, :index)

    get("/transactions-csv", AddressTransactionController, :transactions_csv)

    get("/token-autocomplete", ChainController, :token_autocomplete)

    get("/token-transfers-csv", AddressTransactionController, :token_transfers_csv)

    get("/internal-transactions-csv", AddressTransactionController, :internal_transactions_csv)

    get("/logs-csv", AddressTransactionController, :logs_csv)

    get("/chain-blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/token-counters", Tokens.TokenController, :token_counters)

    get("/*path", PageNotFoundController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
<div class="card">
  <div class="card-body">
    <h1 class="card-title"><%= gettext "Input" %> </h1>
    <!-- Input -->
    <%= case @decoded_input_data do %>
    <% {:error, :contract_not_verified, candidates} -> %>
    <div class="alert alert-info">
      <%= gettext "To see accurate decoded input data, the contract must be verified." %>
      <%= case @transaction do %>
        <% %{to_address: %{hash: hash}} -> %>
          <% path = address_verify_contract_path(@conn, :new, hash) %>
          <%= gettext "Verify the contract " %><a href="<%= path %>"><%= gettext "here" %></a>
        <% _ -> %>
          <%= nil %>
      <% end %>
    </div>
    <%= unless Enum.empty?(candidates) do %>
      <h3><%= gettext "Potential matches from our contract method database:" %></h3>
      <%= gettext "IMPORTANT: This information is a best guess based on similar functions from other verified contracts." %>
      <%= gettext "To have guaranteed accuracy, use the link above to verify the contract's source code." %>

      <%= for {:ok, method_id, text, mapping} <- candidates do %>
        <hr/>
        <h3><%= text %>: </h3>

        <%= render(BlockScoutWeb.TransactionView, "_decoded_input_body.html", method_id: method_id, text: text, mapping: mapping) %>
      <% end %>
    <% end %>
    <% {:ok, method_id, text, mapping} -> %>
      <%= render(BlockScoutWeb.TransactionView, "_decoded_input_body.html", method_id: method_id, text: text, mapping: mapping) %>
    <% {:error, :contract_verified, candidates} -> %>
      <h3><%= gettext "Potential matches from our contract method database:" %></h3>
      <%= for {:ok, method_id, text, mapping} <- candidates do %>
        <hr/>
        <h3><%= text %>: </h3>
        <%= render(BlockScoutWeb.TransactionView, "_decoded_input_body.html", method_id: method_id, text: text, mapping: mapping) %>
      <% end %>
    <% _ -> %>
        <div class="alert alert-danger">
          <%= gettext "Failed to decode input data." %>
        </div>
    <% end %>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex
<div class="table-responsive text-center">
  <table style="color: black;" summary="<%= gettext "Transaction Inputs" %>" class="table thead-light table-bordered">
  <%= if !assigns[:error] do %>
    <tr>
    <td><%= gettext "Method Id" %></td>
    <td colspan="3"><code>0x<%= @method_id %></code></td>
    </tr>
  <% end %>
  <tr>
  <td><%= if assigns[:error], do: gettext("Error"), else: gettext("Call") %></td>
  <td colspan="3"><code><%= @text %></code></td>
  </tr>
  </table>
</div>

<% max_length = get_max_length() %>
<%= unless Enum.empty?(@mapping) do %>
  <div class="table-responsive text-center">
    <table style="color: black; table-layout: fixed;" summary="<%= gettext "Transaction Inputs" %>" class="table thead-light table-bordered">
      <tr>
      <th scope="col" style="width: 10%;"><%= gettext "Name" %></th>
      <th scope="col" style="width: 10%;"><%= gettext "Type" %></th>
      <th scope="col"><%= gettext "Data" %></th>
      <tr>
      <%= for {name, type, value} <- @mapping do %>
        <tr>
          <td><%= name %></td>
          <td><%= type %></td>
          <td align=left>
            <%= case BlockScoutWeb.ABIEncodedValueView.value_html(type, value) do %>
              <% :error -> %>
                <div class="alert alert-danger">
                  <%= gettext "Error rendering value" %>
                </div>
              <% _value -> %>
                <%= case BlockScoutWeb.ABIEncodedValueView.copy_text(type, value) do %>
                  <% :error -> %>
                    <%= nil %>
                  <% copy_text -> %>
                    <span
                      aria-label='<%= gettext "Copy Value" %>'
                      class="btn-copy-ico"
                      data-clipboard-text='<%= copy_text %>'
                      data-placement="top"
                      data-toggle="tooltip"
                      style="float: left;height: 20px;"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.5 32.5" width="25" height="25">
                        <path fill-rule="evenodd" d="M23.5 20.5a1 1 0 0 1-1-1v-9h-9a1 1 0 0 1 0-2h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zm-3-7v10a1 1 0 0 1-1 1h-10a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1zm-2 1h-8v8h8v-8z"/>
                      </svg>
                    </span>
                <% end %>
                <% template = BlockScoutWeb.ABIEncodedValueView.value_html(type, value)%>
                <% string = template_to_string(template) %>
                <pre class="transaction-input-text pre-wrap" style="margin-bottom: 0px;"><code style="line-height: 25px;"><%= if String.length(string) > max_length do %><div data-input-container><% input = trim(max_length, string) %><%= input[:show] %><span data-placeholder-dots>...</span><button type="button" class="btn-line" id="button-expand" aria-label="Expand" button-expand-input><%= gettext "Expand" %></button><span class="more d-none" data-hidden-text><%= input[:hide] %></span><button type="button" class="btn-line d-none" aria-label="Collapse" button-collapse-input><%= gettext "Collapse" %></button></div><% else %><%= template %><% end %></code></pre>
              <% end %>
          </td>
        </tr>
      <% end %>
    </table>
   </div>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_emission_reward_tile.html.eex
<div class="tile tile-type-emission-reward fade-in" data-identifier-hash="<%= @validator.block.hash %>">
  <div class="row tile-body">
    <div class="col-md-2 d-flex flex-row flex-md-column align-items-left justify-content-start justify-content-lg-center mb-1 mb-md-0 pl-md-4">
      <span class="tile-label">
        <%= gettext("Emission Contract") %>
      </span>
      <span class="tile-status-label ml-2 ml-md-0">
        <%= gettext("Success") %>
      </span>
    </div>
    <div class="col-md-7 col-lg-8 d-flex flex-column pr-2 pr-sm-2 pr-md-0">
      <%= link(
        @validator.block.hash,
        to: block_path(BlockScoutWeb.Endpoint, :show, @validator.block.hash),
        class: "text-truncate") %>
      <span class="text-nowrap">
        <%= @emission_funds |> BlockScoutWeb.AddressView.address_partial_selector(nil, @current_address) |> BlockScoutWeb.RenderHelpers.render_partial() %>
        &rarr;
        <%= @validator |> BlockScoutWeb.AddressView.address_partial_selector(nil, @current_address) |> BlockScoutWeb.RenderHelpers.render_partial() %>
      </span>
      <span class="d-flex flex-md-row flex-column mt-3 mt-md-0">
        <span class="tile-title">
          <%= format_wei_value(@emission_funds.reward, :ether) %>
        </span>
      </span>
    </div>
    <div class="col-md-3 col-lg-2 d-flex flex-row flex-md-column flex-nowrap justify-content-start text-md-right mt-3 mt-md-0">
      <span class="mr-2 mr-md-0 order-1">
        <%= @validator |> block_number() |> BlockScoutWeb.RenderHelpers.render_partial() %>
      </span>
      <span class="mr-2 mr-md-0 order-2" data-from-now="<%= block_timestamp(@validator) %>"></span>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_link.html.eex
<%= link(@transaction_hash,
    to: transaction_path(BlockScoutWeb.Endpoint, :show, @transaction_hash),
    "data-test": "transaction_hash_link",
    class: "text-truncate") %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_link_to_token_symbol.html.eex
<%= link(token_symbol(@transfer.token), to: token_path(BlockScoutWeb.Endpoint, :show, @transfer.token.contract_address_hash), "data-test": "token_link") %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_metatags.html.eex
<%= if assigns[:transaction] do %>
  <title>
    <%= gettext(
          "Transaction %{transaction} - %{subnetwork} Explorer",
          transaction: to_string(@transaction.hash),
          subnetwork: BlockScoutWeb.LayoutView.subnetwork_title()
        ) %>
  </title>

  <meta name="description" content="<%= gettext "View transaction %{transaction} on %{subnetwork}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
  <meta name="keywords" content="<%= gettext "Transaction %{transaction}, %{subnetwork} %{transaction}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
<% else %>
  <%= BlockScoutWeb.LayoutView.render("_default_title.html") %>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
<% status = BlockScoutWeb.TransactionView.transaction_status(@transaction) %>
<div class="tile tile-type-<%= BlockScoutWeb.TransactionView.type_suffix(@transaction) %> fade-in" data-test="<%= BlockScoutWeb.TransactionView.type_suffix(@transaction) %>" data-identifier-hash="<%= @transaction.hash %>">
  <div class="row" data-test="chain_transaction">
    <div class="col-md-2 d-flex flex-row flex-md-column align-items-left justify-content-start justify-content-lg-center mb-1 mb-md-0 pl-md-4">
      <span class="tile-label" data-test="transaction_type"> <%= BlockScoutWeb.TransactionView.transaction_display_type(@transaction) %></span>
      <div class="tile-status-label ml-2 ml-md-0" data-test="transaction_status"><%= BlockScoutWeb.TransactionView.formatted_result(status) %></div>
    </div>
    <div class="col-md-7 col-lg-8 d-flex flex-column pr-2 pr-sm-2 pr-md-0">
      <%= render BlockScoutWeb.TransactionView, "_link.html", transaction_hash: @transaction.hash %>
      <span class="text-nowrap">
        <%= render BlockScoutWeb.AddressView, "_link.html", address: @transaction.from_address, contract: BlockScoutWeb.AddressView.contract?(@transaction.from_address), use_custom_tooltip: false %>
        &rarr;
        <%= if @transaction.to_address_hash do %>
          <%= render BlockScoutWeb.AddressView, "_link.html", address: @transaction.to_address, contract: BlockScoutWeb.AddressView.contract?(@transaction.to_address), use_custom_tooltip: false %>
        <% else %>
          <%= gettext("Contract Address Pending") %>
        <% end %>
      </span>
      <span class="d-flex flex-md-row flex-column mt-3 mt-md-0">
        <span class="tile-title"><%= BlockScoutWeb.TransactionView.value(@transaction, include_label: false) %> <%= gettext "Ether" %></span>
        <span class="ml-0 ml-md-1 text-nowrap"> <%= BlockScoutWeb.TransactionView.formatted_fee(@transaction, denomination: :ether, include_label: false) %> <%= gettext "TX Fee" %></span>
      </span>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/invalid.html.eex
<section class="container">
  <div class="row">
    <div class="col-12"> 
      <div class="card">
        <div class="card-body">
          <h1 class="card-title"><%= gettext "Invalid Transaction Hash" %></h1>
          <div class="tile tile-muted text-center">
            <span> <span class="font-weight-bold"><%= @transaction_hash %></span> <%= gettext "is not a valid transaction hash" %> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>